#!/bin/bash
rsync -Lrtpv --delete --backup-dir /tmp/backup --size-only /Users/iain/Pictures/Published/thumbs/ jphuquoc@soulflyer.co.uk:Pictures/thumbs/
rsync -Lrtpv --delete --backup-dir /tmp/backup --size-only /Users/iain/Pictures/Published/watermarked-1024/ jphuquoc@soulflyer.co.uk:Pictures/watermarked-1024/
