#!/bin/bash
# Add n to the list of options to do a dry run
BACKUPDIR=/Users/iain/backup
echo "backing up Pictures/Published"
rsync -vaib $@ /Users/iain/Pictures/Published/ mimi.local:/Users/iain/Pictures/Published

echo "backing up master copies"
rsync -vaib $@ /Users/iain/Pictures/Photos/ mimi.local:/Users/iain/Pictures/Photos

# Pull stuff from the Music directory on mimi first
# echo "fetching music stuff from mimi"
# rsync -rtpogvKlb --backup-dir=/Users/iain/backupMusic/Music mimi.local:/Users/iain/Music/ /Users/iain/Music/

echo "backing up OfflinePhotos"
rsync -vaib --delete --backup-dir=$BACKUPDIR $@ /Volumes/Sony2T/OfflinePhotos/ mimi.local:/Users/iain/Pictures/OfflinePhotos
