#!/bin/bash
rsync -vai ~/Pictures/Photos /Volumes/Iomega/iain/Pictures/
rsync -vai --delete  \
    --exclude=.Trash --exclude=Library --exclude=Downloads \
    --exclude=Movies --exclude=Desktop \
     ~ /Volumes/Iomega/
rsync -vai --delete  /Volumes/Brick2/OfflinePhotos/ /Volumes/Iomega/OfflinePhotos
