#!/bin/bash
rsync -vai ~/Pictures/Photos /Volumes/Iomega/iain/Pictures/
rsync -vai  \
    --exclude=.Trash --exclude=Library --exclude=Downloads \
    --exclude=Movies --exclude=Desktop --exclude=VirtualBox* \
     ~ /Volumes/Iomega/
rsync -vai  /Volumes/Sony2T/OfflinePhotos/ /Volumes/Iomega/OfflinePhotos
