#!/bin/bash
# Add n to the list of options to do a dry run
# Add or remove  b to control backups

rsync  -rtpogvKlb $2  --delete  --backup-dir /Volumes/$1/backup --include-from=/Users/iain/bin/excludes  /Users/iain/ /Volumes/$1/iain/

# Backup /usr/local Might be better to do ''brew bundle dump' and restore from that
# rsync -rtpogvKl $2 --delete /usr/local /Volumes/$1/usr-local

# rsync -rtpogvKl  --delete --backup-dir /Volumes/$1/backup /Applications/ /Volumes/$1/Applications/
