#!/bin/bash
rsync -vai --delete  \
    --exclude=.Trash --exclude=Library --exclude=Downloads --exclude=Movies \
     ~ /Volumes/Iomega/
rsync -vai --delete  /Volumes/Silver/ /Volumes/Iomega/OfflinePhotos
